const Dummydata = [
  {
    id: "1200",
    project: "office ui",
    task: "time screen",
    remarks: "creating dash board",
    worked: "3",
    clocked: "8",
    utilised: "8.30",
    efficiency: "efficiency:100%",

    project1: "camera",
    task1: "take",
    remarks1: "creating dash board ",
    worked1: "7",
    clocked1: "8",
    utilised1: "9.30",
    efficiency1: "efficiency:100%",
    project2: "camera",
    task2: "take",
    remarks2: "creating dash board ",
    worked2: "7",
    clocked2: "8",
    utilised2: "9.30",
    efficiency2: "efficiency:100%",
  },

  {
    id: "1201",
    project: "camera",
    task: "take",
    remarks: "creating dash board ",
    worked: "7",
    clocked: "8",
    utilised: "9.30",
    efficiency: "efficiency:100%",

    project1: "camera",
    task1: "take",
    remarks1: "creating dash board ",
    worked1: "7",
    clocked1: "8",
    utilised1: "9.30",
    efficiency1: "efficiency:100%",

    project2: "camera",
    task2: "take",
    remarks2: "creating dash board ",
    worked2: "7",
    clocked2: "8",
    utilised2: "9.30",
    efficiency2: "efficiency:100%",
  },

  {
    id: "1202",
    project: "cartoon ui",
    task: "flash dashboard screen",
    remarks: "creating dash board",
    worked: "4",
    clocked: "1",
    utilised: "5",
    efficiency: "tour",

    project1: "camera",
    task1: "take",
    remarks1: "creating dash board ",
    worked1: "7",
    clocked1: "8",
    utilised1: "9.30",
    efficiency1: "efficiency:100%",

    project2: "camera",
    task2: "take",
    remarks2: "creating dash board ",
    worked2: "7",
    clocked2: "8",
    utilised2: "9.30",
    efficiency2: "efficiency:100%",
  },

  {
    id: "1203",
    project: "3d ui",
    task: "rim screen",
    remarks: "creating dash board",
    worked: "3",
    clocked: "6",
    utilised: "2.30",
    efficiency: "efficiency:100%",

    project1: "camera",
    task1: "take",
    remarks1: "creating dash board ",
    worked1: "7",
    clocked1: "8",
    utilised1: "9.30",
    efficiency1: "efficiency:100%",
    project2: "camera",
    task2: "take",
    remarks2: "creating dash board ",
    worked2: "7",
    clocked2: "8",
    utilised2: "9.30",
    efficiency2: "efficiency:100%",
  },
  {
    id: "1204",
    project: "faced  ui",
    task: " screen",
    remarks: "creating dash board",
    worked: "3",
    clocked: "8",
    utilised: "4.30",
    efficiency: "efficiency:100%",
    project1: "camera",
    task1: "take",
    remarks1: "creating dash board ",
    worked1: "7",
    clocked1: "8",
    utilised1: "9.30",
    efficiency1: "efficiency:100%",
    project2: "camera",
    task2: "take",
    remarks2: "creating dash board ",
    worked2: "7",
    clocked2: "8",
    utilised2: "9.30",
    efficiency2: "efficiency:100%",
  },

  {
    id: "1205",
    project: "login ui",
    task: "dashboard screen",
    remarks: "creating dash board",
    worked: "3",
    clocked: "3",
    utilised: "4.30",
    efficiency: "efficiency:100%",

    project1: "camera",
    task1: "take",
    remarks1: "creating dash board ",
    worked1: "7",
    clocked1: "8",
    utilised1: "9.30",
    efficiency1: "efficiency:100%",
    project2: "camera",
    task2: "take",
    remarks2: "creating dash board ",
    worked2: "7",
    clocked2: "8",
    utilised2: "9.30",
    efficiency2: "efficiency:100%",
  },
];

export default Dummydata;

export const MytaskDummmy = [
  {
    project: "",
    task: "",
    remarks: "",
    worked: "",
    clocked: "",
    utilised: "",
    efficiency: "",
  },
];

export const inititalState2 = [
  {
    Name: `anand`,
    "Date applied": `13th oct 2021`,
    From: `01 nov 2021`,
    To: `02 nov 2021`,
    Days: `3`,
    LOP: `0`,
    particular: `dewali`,
    "L1 approver remarks": "sandeep :approved",
    "L2 approver & remarks": "parimala",
    "Hr approver & remarks": "approved",
  },
];
